# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c2573ac37775c8b03204240f0522c27ebed3de8d9341d07ccdb8dcd8af590cfcf600abfa44e4df4220fda40914556e0755b54273c99a755fa433a122dee9ac5

test:
  secret_key_base: 28e7f70023bd82e00aed2358a62d0783a19af5c3fc09c598c54c7ff7326bf5638fdfde94f21c6722cd83b0253371893f2b24f5002806b580da24b4fff6c6b3db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
